-- ==========================================
-- SCRIPT DE INICIALIZAÇÃO DO BANCO DE DADOS
-- Projeto de Casamento: Amanda & Guilherme
-- ==========================================

-- Tabela de convidados
-- Armazena todos os convidados oficiais, permitindo busca e atualização de presença (RSVP)
CREATE TABLE convidados (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  confirmed BOOLEAN DEFAULT NULL, -- null=pendente, true=confirmado, false=recusado
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar buscas rápidas por nome (case-insensitive)
CREATE INDEX idx_convidados_name_ilike ON convidados (name);

-- CARGA INICIAL DE CONVIDADOS (99 Convidados)
-- Você pode copiar e rodar este comando inteiro no editor SQL do Supabase
INSERT INTO convidados (name) VALUES 
('Patricia'),
('Tarciano'),
('Sophia'),
('Thiago'),
('Helena'),
('Vo Manuel'),
('Vo Sebastião'),
('Anderson'),
('Val'),
('Cristiano'),
('Iris'),
('Tio Agnel'),
('Tia Nilza'),
('Tia Cleuza'),
('Taina'),
('Tia Jo'),
('Tio zé'),
('Primo Fábio'),
('Neide'),
('Amanda'),
('Prima Fabi'),
('Esposo da Tia Fabi'),
('Senhor Luis'),
('Larissa'),
('Tauany'),
('Cadu'),
('Hélder primo'),
('Renata'),
('Maria Alice'),
('Maria Cecilia'),
('Rose tia'),
('Tia Lindaura'),
('Tia Fatinha'),
('Edna'),
('Yasmin'),
('Manu'),
('Mário'),
('Valdinete'),
('Mara'),
('Ingrid'),
('Julia'),
('Ashiley'),
('Andreia'),
('Henrique'),
('Andreza'),
('Daniel'),
('Miguel'),
('Gabriel'),
('Joyce'),
('Ana'),
('Rebeca'),
('Marise'),
('Samuel'),
('Livia'),
('Jared'),
('Natalia'),
('Matteo'),
('Diogo'),
('Leticia'),
('Matheus'),
('Luighi'),
('Nice'),
('Waldirene'),
('Viviane'),
('Lucas'),
('Bruno'),
('Esposo da Val'),
('Simone'),
('Wagner'),
('Vanderlei'),
('Vilma'),
('David'),
('Benjamin'),
('Heitor'),
('Rubinho'),
('Guilherme'),
('Isabela'),
('Claudia'),
('Adilson'),
('Irmã Olívia'),
('Irmão Francisco'),
('Irmã Neusa'),
('Irmão Edivaldo'),
('Irmã Cristina'),
('Cintia'),
('Marta'),
('Denis'),
('Ana Paula'),
('Ana Alice'),
('Ana Luiza'),
('Tio Dan');
